### ISSUE TITLE
When the bot is called as a member an error is thrown

### ISSUE THREAD

**Issue by RealYusufIsmail** [YDWK/YDWK#101]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest YDWK version](https://search.maven.org/artifact/io.github.realyusufismail/ydwk)

### Steps to reproduce

val bot: Member = event.guild?.botAsMember ?: return

### What is expected?

No error

### What is actually happening?

Receiving this error 
```
java.lang.IllegalStateException: Bot is not a member of this guild
	at io.github.ydwk.ydwk.impl.entities.GuildImpl.getBotAsMember(GuildImpl.kt:174)
	at io.github.ydwk.bot.commands.moderation.BanCommand.onSlashCommand(BanCommand.kt:32)
	at io.github.ydwk.bot.handler.slash.SlashHandler.onSlashCommand(SlashHandler.kt:62)
	at io.github.ydwk.ydwk.evm.ListenerAdapter.onEvent(ListenerAdapter.kt:618)
	at io.github.ydwk.ydwk.evm.backend.managers.SampleEventManager.emitEvent(SampleEventManager.kt:33)
	at io.github.ydwk.ydwk.impl.YDWKImpl.emitEvent(YDWKImpl.kt:430)
	at io.github.ydwk.ydwk.evm.handler.handlers.interactions.InteractionCreateHandler.start(InteractionCreateHandler.kt:42)
	at io.github.ydwk.ydwk.ws.WebSocketManager.onEventType(WebSocketManager.kt:529)
	at io.github.ydwk.ydwk.ws.WebSocketManager.onOpCode(WebSocketManager.kt:348)
	at io.github.ydwk.ydwk.ws.WebSocketManager.onEvent(WebSocketManager.kt:341)
	at io.github.ydwk.ydwk.ws.WebSocketManager.handleMessage(WebSocketManager.kt:219)
	at io.github.ydwk.ydwk.ws.WebSocketManager.onTextMessage(WebSocketManager.kt:200)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:353)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:266)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:244)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:969)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:752)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

```

### Any additional comments?

no

**Comment by RealYusufIsmail** [comment]
The bot as a member might not be cached
